# --- 4. Service do Banco de Dados (PostgreSQL) ---
# Expõe o banco de dados internamente no cluster (ClusterIP).
# A aplicação usará o nome 'book-catalog-database' para se conectar.
apiVersion: v1
kind: Service
metadata:
  name: book-catalog-database
  namespace: default
spec:
  selector:
    app: book-catalog-database
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP